### ISSUE TITLE
CI server should build and tag

### ISSUE THREAD

**Issue by igoratron** [FundingCircle/sass-common#32]
Currently, we are forced to manually build and commit the `dist` folder whenever we merge a branch. Additionally, we need to manually tag the repository when we do a release. It would be preferable if we could automate this and have the CI server build the `dist` folder and tag it whenever a branch is merged and the tests pass.

**Considerations**
- do we let the CI server decide what version to tag the folder under? should it pick up the version from the bower/package json? Or should we have `-SNAPSHOT`-like tag crated automatically and an official version would only be released when someone manually tags/presses a button in CI?

**Comment by RazvanDH** [comment]
That would be great. 

As for the tag goes, I believe it should pick up the version from bower/package.

**Comment by sgerrand** [comment]
@igoratron: That would mean the CI server/service would need permissions to create commits and other object types in our repository. So long as this risk is understood.

**Comment by sgerrand** [comment]
> should it pick up the version from the bower/package json

* which manifest takes priority?
* what if the version doesn't change?

I don't see an issue with manually tagging a release - this implies that each release is a considered action, not a by-product. :smile_cat:
